### ISSUE TITLE
ブロックテーマでtitleタグが２重に出力される

### ISSUE THREAD

**Issue by ddryo** [ddryo/seo-simple-pack#18]
既存のタイトルタグ削除処理がブロックテーマだと動作していないっぽい。
順序の関係か。

**Comment by t-hamano** [comment]
Yoast SEOを参考にしたところ、ブロックテーマでは `pre_get_document_title` フックで既存のtitleタグを書き換えているようです。

こういう感じでフックしている
https://github.com/Yoast/wordpress-seo/blob/b722cce4b8b8d5ad53c5fd312332522f32aad249/src/integrations/front-end-integration.php#L225-L226

`output_meta_tags()` 側ではtitleタグを出力しないように、この辺りで`wp_is_block_theme()` でチェックすればよさそう
https://github.com/ddryo/seo-simple-pack/blob/4ff95449e384d2786bf885c0dfbda707faf72338/class/output.php#L169
