### ISSUE TITLE
投稿アーカイブページでcanonical URLが正しく表示されない

### ISSUE THREAD

**Issue by t-hamano** [ddryo/seo-simple-pack#22]
「設定」>「ホームページの表示」>「投稿ページ」を指定し、その投稿ページに指定した固定ページを開いた時に、canonical URL が正しく表示されません。
本来はその固定ページのパーマリンクとなるはずですが、ループ内の投稿のパーマリンクとなってしまいます。

https://github.com/ddryo/seo-simple-pack/blob/da92f9675d3fecf5bf0e8e5675bc8df29f1ced11/class/output.php#L561

この箇所を以下のように、引数に明示的に ID を与えてあげれば改善されるのではないかと思います。

```php
$canonical      = $meta_canonical ?: get_permalink( self::$obj->ID ); 
```

**Comment by ddryo** [comment]
ありがとうございます！

**Comment by w3guy** [comment]
@ddryo i will love to reach out to you with a proposal. let me know how to email you please
